In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('ChurnData.csv')
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [30]:
corr=df.corr()
corr_target=abs(corr['churn'])
relavant_feature=corr_target[corr_target>0.3]
relavant_feature

tenure      0.376860
employ      0.337969
callcard    0.311451
loglong     0.336869
churn       1.000000
Name: churn, dtype: float64

In [4]:
inp_data=pd.DataFrame()
inp_data

Empty DataFrame
Columns: []
Index: []

In [31]:
inp_data = df[['tenure','employ','callcard','loglong']]
inp_data

tenure  employ  callcard  loglong
0      11.0     5.0       1.0    1.482
1      33.0     0.0       0.0    2.246
2      23.0     2.0       0.0    1.841
3      38.0    10.0       1.0    1.800
4       7.0    15.0       1.0    1.960
..      ...     ...       ...      ...
195    55.0    23.0       1.0    2.854
196    34.0     7.0       1.0    1.792
197     6.0    10.0       1.0    1.348
198    24.0     5.0       1.0    2.163
199    61.0    22.0       1.0    2.824

[200 rows x 4 columns]

In [32]:
from sklearn.preprocessing import MinMaxScaler
mmc=MinMaxScaler()
inp_data=mmc.fit_transform(inp_data)
inp_data

array([[0.14084507, 0.11363636, 1.        , 0.34357196],
       [0.45070423, 0.        , 0.        , 0.5328214 ],
       [0.30985915, 0.04545455, 0.        , 0.43249938],
       [0.52112676, 0.22727273, 1.        , 0.42234332],
       [0.08450704, 0.34090909, 1.        , 0.46197672],
       [0.94366197, 0.54545455, 1.        , 0.72702502],
       [0.57746479, 0.18181818, 1.        , 0.49913302],
       [0.11267606, 0.04545455, 0.        , 0.24027743],
       [0.47887324, 0.47727273, 1.        , 0.44017835],
       [0.67605634, 0.43181818, 1.        , 0.60886797],
       [0.77464789, 0.27272727, 1.        , 0.77136487],
       [0.64788732, 0.27272727, 1.        , 0.71488729],
       [0.77464789, 0.54545455, 1.        , 0.80876889],
       [0.95774648, 0.52272727, 1.        , 0.81050285],
       [0.21126761, 0.11363636, 0.        , 0.42036165],
       [0.04225352, 0.13636364, 0.        , 0.27966312],
       [0.36619718, 0.25      , 0.        , 0.46197672],
       [0.71830986, 0.02272727,

In [33]:
inp_data_nor=pd.DataFrame(inp_data,columns=['tenure','employ','callcard','loglong'])
inp_data_nor

tenure    employ  callcard   loglong
0    0.140845  0.113636       1.0  0.343572
1    0.450704  0.000000       0.0  0.532821
2    0.309859  0.045455       0.0  0.432499
3    0.521127  0.227273       1.0  0.422343
4    0.084507  0.340909       1.0  0.461977
..        ...       ...       ...       ...
195  0.760563  0.522727       1.0  0.683428
196  0.464789  0.159091       1.0  0.420362
197  0.070423  0.227273       1.0  0.310379
198  0.323944  0.113636       1.0  0.512262
199  0.845070  0.500000       1.0  0.675997

[200 rows x 4 columns]

In [34]:
out_data = [df['churn']]
out_data

[0      1.0
 1      1.0
 2      0.0
 3      0.0
 4      0.0
       ... 
 195    0.0
 196    0.0
 197    0.0
 198    1.0
 199    0.0
 Name: churn, Length: 200, dtype: float64]

In [35]:
from sklearn.cluster import KMeans

In [36]:
kmeans = KMeans(n_clusters = 2,max_iter=50000)
kmeans

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=50000,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [37]:
kModel = kmeans.fit(inp_data_nor)

In [38]:
kModel.labels_

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1])

In [39]:
pd.crosstab(out_data, kModel.labels_)

col_0   0    1
churn         
0.0    29  113
1.0    30   28

In [40]:
(29+28)/(28+28+113+30)

0.2864321608040201

Work on heart dataset

In [41]:
df=pd.read_csv("heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [42]:
X=df.drop('target',1)
Y=df.target

In [43]:
cor=df.corr()
cor_target=abs(cor['target'])
relevant_feature=cor_target[cor_target>=0.4]
relevant_feature

cp         0.433798
thalach    0.421741
exang      0.436757
oldpeak    0.430696
target     1.000000
Name: target, dtype: float64

In [45]:
X_new=df[['cp','thalach','exang','oldpeak']]
featureset=X_new
from sklearn.preprocessing import MinMaxScaler
x=featureset.values
x

array([[  3. , 150. ,   0. ,   2.3],
       [  2. , 187. ,   0. ,   3.5],
       [  1. , 172. ,   0. ,   1.4],
       ...,
       [  0. , 141. ,   0. ,   3.4],
       [  0. , 115. ,   1. ,   1.2],
       [  1. , 174. ,   0. ,   0. ]])

In [47]:
mmc=MinMaxScaler()
feature_mtx=mmc.fit_transform(x)
X_new=feature_mtx
X_new

array([[1.        , 0.60305344, 0.        , 0.37096774],
       [0.66666667, 0.88549618, 0.        , 0.56451613],
       [0.33333333, 0.77099237, 0.        , 0.22580645],
       ...,
       [0.        , 0.53435115, 0.        , 0.5483871 ],
       [0.        , 0.33587786, 1.        , 0.19354839],
       [0.33333333, 0.78625954, 0.        , 0.        ]])

In [48]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=2, max_iter=50000)
kmodel=kmeans.fit(X_new)

In [49]:
pd.crosstab(Y,kmodel.labels_)

col_0     0   1
target         
0        62  76
1       142  23