In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [2]:
path = 'Social_Network_Ads.csv'
df = pd.read_csv(path)
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [18]:
df=pd.get_dummies(df)
df.head()

User ID  Age  EstimatedSalary  Purchased  Female  Male  Female  Male  \
0  15624510   19            19000          0       0     1       0     1   
1  15810944   35            20000          0       0     1       0     1   
2  15668575   26            43000          0       1     0       1     0   
3  15603246   27            57000          0       1     0       1     0   
4  15804002   19            76000          0       0     1       0     1   

   Female  Male  Female  Male  Female  Male  Female  Male  Gender_Female  \
0       0     1       0     1       0     1       0     1              0   
1       0     1       0     1       0     1       0     1              0   
2       1     0       1     0       1     0       1     0              1   
3       1     0       1     0       1     0       1     0              1   
4       0     1       0     1       0     1       0     1              0   

   Gender_Male  
0            1  
1            1  
2            0  
3            0  
4            1

In [19]:
X = df[['Age','EstimatedSalary','Female','Male']] .values  #.astype(float)
X[0:5]

array([[   19, 19000,     0,     0,     0,     0,     0,     0,     1,
            1,     1,     1,     1,     1],
       [   35, 20000,     0,     0,     0,     0,     0,     0,     1,
            1,     1,     1,     1,     1],
       [   26, 43000,     1,     1,     1,     1,     1,     1,     0,
            0,     0,     0,     0,     0],
       [   27, 57000,     1,     1,     1,     1,     1,     1,     0,
            0,     0,     0,     0,     0],
       [   19, 76000,     0,     0,     0,     0,     0,     0,     1,
            1,     1,     1,     1,     1]], dtype=int64)

In [20]:
y = df['Purchased'].values
y[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (320, 14) (320,)
Test set: (80, 14) (80,)


In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
k = 5
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [27]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([0, 0, 0, 0, 1], dtype=int64)

In [28]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.859375
Test set Accuracy:  0.8
