In [16]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [17]:
df = pd.read_csv("teleCust1000t.csv")
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [36]:
df.corr()

region    tenure       age   marital   address    income        ed  \
region   1.000000  0.016388  0.015034 -0.080637  0.010320  0.023765 -0.057952   
tenure   0.016388  1.000000  0.490217  0.154171  0.522952  0.242912 -0.109797   
age      0.015034  0.490217  1.000000 -0.014433  0.660435  0.327948 -0.154857   
marital -0.080637  0.154171 -0.014433  1.000000 -0.012051 -0.043984  0.001400   
address  0.010320  0.522952  0.660435 -0.012051  1.000000  0.226781 -0.128330   
income   0.023765  0.242912  0.327948 -0.043984  0.226781  1.000000  0.113939   
ed      -0.057952 -0.109797 -0.154857  0.001400 -0.128330  0.113939  1.000000   
employ   0.016335  0.520288  0.670047 -0.002891  0.463291  0.516349 -0.228580   
retire   0.005595  0.171143  0.429440 -0.078109  0.292503 -0.083651 -0.114229   
gender   0.050596  0.023533 -0.011419  0.008345  0.008363  0.038706  0.006704   
reside  -0.065158 -0.036592 -0.254993  0.625999 -0.201645 -0.097591  0.021045   
custcat -0.023771  0.166691  0.056909  0.083836  0.067913  0.134525  0.193864   

           employ    retire    gender    reside   custcat  
region   0.016335  0.005595  0.050596 -0.065158 -0.023771  
tenure   0.520288  0.171143  0.023533 -0.036592  0.166691  
age      0.670047  0.429440 -0.011419 -0.254993  0.056909  
marital -0.002891 -0.078109  0.008345  0.625999  0.083836  
address  0.463291  0.292503  0.008363 -0.201645  0.067913  
income   0.516349 -0.083651  0.038706 -0.097591  0.134525  
ed      -0.228580 -0.114229  0.006704  0.021045  0.193864  
employ   1.000000  0.277401  0.046016 -0.134683  0.110011  
retire   0.277401  1.000000  0.053906 -0.140120  0.008908  
gender   0.046016  0.053906  1.000000  0.016556 -0.004966  
reside  -0.134683 -0.140120  0.016556  1.000000  0.082022  
custcat  0.110011  0.008908 -0.004966  0.082022  1.000000

In [37]:
df_new=pd.DataFrame()

In [39]:
df_new[['tenure','income','ed','employ','custcat']]=df[['tenure','income','ed','employ','custcat']]

In [40]:
df_new['custcat'].value_counts()

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [42]:
X = df_new[[ 'tenure',  'income', 'ed', 'employ']] .values  #.astype(float)
X[0:5]

array([[ 13.,  64.,   4.,   5.],
       [ 11., 136.,   5.,   5.],
       [ 68., 116.,   1.,  29.],
       [ 33.,  33.,   2.,   0.],
       [ 23.,  30.,   1.,   2.]])

In [43]:
y = df_new['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (800, 4) (800,)
Test set: (200, 4) (200,)


In [58]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
k = 3
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [69]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([1, 4, 4, 4, 4], dtype=int64)

In [70]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.61125
Test set Accuracy:  0.255
