In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
churn_df = pd.read_csv("ChurnData.csv")
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [3]:
churn_df.corr()

tenure       age   address    income        ed    employ  \
tenure    1.000000  0.431802  0.456328  0.109383 -0.070503  0.445755   
age       0.431802  1.000000  0.746566  0.211275 -0.071509  0.622553   
address   0.456328  0.746566  1.000000  0.132807 -0.145550  0.520926   
income    0.109383  0.211275  0.132807  1.000000  0.141241  0.345161   
ed       -0.070503 -0.071509 -0.145550  0.141241  1.000000 -0.213886   
employ    0.445755  0.622553  0.520926  0.345161 -0.213886  1.000000   
equip    -0.117102 -0.071357 -0.148977 -0.010741  0.488041 -0.174470   
callcard  0.426530  0.170404  0.209204 -0.019969 -0.071178  0.266612   
wireless -0.070590 -0.065527 -0.146478 -0.029635  0.267670 -0.101187   
longmon   0.763134  0.373547  0.421782  0.041808 -0.072735  0.363386   
tollmon   0.100214  0.053595 -0.015564 -0.003701 -0.000712  0.117962   
equipmon -0.043274 -0.030402 -0.125212  0.000275  0.492999 -0.141651   
cardmon   0.489857  0.203202  0.297395 -0.013513 -0.070990  0.219413   
wiremon   0.043067 -0.003685 -0.113143 -0.027998  0.288571 -0.045539   
longten   0.796355  0.393370  0.447256  0.048374 -0.083032  0.385254   
tollten   0.398869  0.187221  0.129141 -0.000262 -0.016257  0.240498   
cardten   0.676920  0.336903  0.406964  0.019358 -0.069499  0.309183   
voice    -0.050686  0.019555 -0.069627  0.085525  0.233628 -0.035922   
pager     0.018791  0.006803 -0.105812  0.056977  0.258698  0.038381   
internet -0.164921 -0.078395 -0.191058  0.102809  0.552996 -0.250044   
callwait -0.009747  0.020002 -0.019967  0.081133 -0.016247  0.119708   
confer    0.080650  0.030625 -0.030494 -0.031556 -0.132215  0.173247   
ebill    -0.099128 -0.048279 -0.172171 -0.041392  0.427315 -0.151965   
loglong   0.864388  0.379413  0.409357  0.065595 -0.054581  0.377186   
logtoll   0.310045  0.093600  0.018386 -0.156498 -0.007227  0.068718   
lninc     0.246353  0.313359  0.212929  0.680313  0.206718  0.540052   
custcat   0.134237  0.041055 -0.016841  0.030725  0.013127  0.131292   
churn    -0.376860 -0.287697 -0.260659 -0.090790  0.216112 -0.337969   

             equip  callcard  wireless   longmon  ...     pager  internet  \
tenure   -0.117102  0.426530 -0.070590  0.763134  ...  0.018791 -0.164921   
age      -0.071357  0.170404 -0.065527  0.373547  ...  0.006803 -0.078395   
address  -0.148977  0.209204 -0.146478  0.421782  ... -0.105812 -0.191058   
income   -0.010741 -0.019969 -0.029635  0.041808  ...  0.056977  0.102809   
ed        0.488041 -0.071178  0.267670 -0.072735  ...  0.258698  0.552996   
employ   -0.174470  0.266612 -0.101187  0.363386  ...  0.038381 -0.250044   
equip     1.000000 -0.087051  0.386735 -0.097618  ...  0.308633  0.623509   
callcard -0.087051  1.000000  0.220118  0.322514  ...  0.251069 -0.067146   
wireless  0.386735  0.220118  1.000000 -0.073043  ...  0.667535  0.343631   
longmon  -0.097618  0.322514 -0.073043  1.000000  ... -0.001372 -0.223929   
tollmon  -0.090516  0.352994  0.462751  0.083771  ...  0.499124  0.036393   
equipmon  0.941065  0.026955  0.527573 -0.070876  ...  0.461458  0.631338   
cardmon  -0.056590  0.629955  0.195387  0.493439  ...  0.216653 -0.129166   
wiremon   0.367579  0.259638  0.885879 -0.020392  ...  0.704724  0.359273   
longten  -0.098271  0.342553 -0.088461  0.984808  ... -0.011369 -0.217916   
tollten  -0.097151  0.292555  0.328256  0.338036  ...  0.390620 -0.017063   
cardten  -0.053837  0.448182  0.047773  0.673179  ...  0.097579 -0.154030   
voice     0.264481  0.226109  0.649721 -0.080503  ...  0.608335  0.243845   
pager     0.308633  0.251069  0.667535 -0.001372  ...  1.000000  0.266193   
internet  0.623509 -0.067146  0.343631 -0.223929  ...  0.266193  1.000000   
callwait -0.034021  0.370878  0.389670  0.032913  ...  0.426690  0.019419   
confer   -0.103499  0.311056  0.382925  0.060614  ...  0.352743 -0.029911   
ebill     0.603133 -0.045058  0.321433 -0.124605  ...  0.288752  0.512987   
loglong  -0.113065  0.351030 -0.042637  0.901631  ...  0.015771 -0.202230  

In [36]:
churn_df = churn_df[['tenure', 'age', 'longmon', 'equip', "loglong"  , 'churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df.head()

tenure   age  longmon  equip  loglong  churn
0    11.0  33.0     4.40    0.0    1.482      1
1    33.0  33.0     9.45    0.0    2.246      1
2    23.0  30.0     6.30    0.0    1.841      0
3    38.0  35.0     6.05    1.0    1.800      0
4     7.0  35.0     7.10    0.0    1.960      0

In [37]:
X = churn_df[['tenure', 'age',  'longmon',   'equip',"loglong" ]]

In [38]:
Y=churn_df['churn']

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2, random_state=4)

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression().fit(X_train,y_train)
LR

C:\Users\a\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
yhat = LR.predict(X_train)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1])

In [43]:
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_train,yhat)
print(cnf_matrix)

[[105  12]
 [ 23  20]]


In [44]:
125/160

0.78125

In [45]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [46]:
yhat = clf.predict(X_train)
yhat [0:5]

array([0, 0, 0, 0, 0])

In [47]:
cnf_matrix = confusion_matrix(y_train,yhat)

print(cnf_matrix)

[[100  17]
 [ 19  24]]


In [48]:
124/160

0.775